= OAuth 2.0 Integration Sample

This sample integrates `spring-security-oauth2-client` and `spring-security-oauth2-resource-server` with *Spring Authorization Server*.

The illustrated OAuth2 flows are:

* authorization flow
* client credentials flow


== Run the Sample

[source]
----
./gradlew build
java -Dspring.config.additional-location=./shared-config/ \
    -Dspring.profiles.active=ssl,ssh-2way \
    -jar authorizationserver/build/libs/authorizationserver.jar &
java -Dspring.config.additional-location=./shared-config/ \
    -Dspring.profiles.active=ssl,ssl-2way,ssl-client,ssl-2way-client \
    -jar resourceserver/build/libs/resourceserver.jar &
java -Dspring.config.additional-location=./shared-config/ \
    -Dspring.profiles.active=ssl-client,ssl-2way-client \
    -jar client/build/libs/client.jar &
----

* Open `http://localhost:39001` in your browser

** *IMPORTANT:* For the Authorization Flow: Make sure to modify your `/etc/hosts` file to avoid problems with session cookie overwrites between `client` and `authorizationserver`. Simply add the entry `127.0.0.1	auth-server`

== SSL Profiles
For each of the applications SSL profiles can be set, such as:
java -Dspring.profiles.active=ssl ...

=== no profiles
Without any SSL profiles set, the applications will run without any SSL.

=== one-way SSL
One level higher is setting ssl/ssl-client. This enables one way SSL without any client certificates.

=== two-way SSL
The highest level is using the -2way profiles in addition. This enables 2-way (mutual) TLS, requiring client certificates.

== Allowed SSL profiles per app

=== client
ssl-client, ssl-2way-client

=== authorizationserver
ssl, ssl-2way

=== resourceserver
ssl-2way, ssl-2way-client (all 2-way)
ssl, ssl-2way

== Interaction Diagram
[ditaa]
....
                                        +---------------+
                                        | Authorization |
                                 +----> |    Server     |
                                 |      +---------------+
            +-------------+      |              ^
            |   Client    +------+              |
            |    App      +------+              |
            +-------------+      |              |
                                 |      +-------+-------+
                                 +----> |   Resource    |
                                        |    Server     |
                                        +---------------+
....