spring:
  main:
    banner-mode: off
    web-application-type: none
  #profiles.active: ssl-2way-auth
  #profiles.active: ssl

app.protocol: http

app:
  test-url: ${app.protocol}://localhost:39001/hello
