app:
  client:
    protocol: http
    host: localhost
    port: 39001
    base-url: ${app.client.protocol}://${app.client.host}:${app.client.port}
  rsrc-server:
    protocol: http
    host: localhost
    port: 39002
    base-url: ${app.rsrc-server.protocol}://${app.rsrc-server.host}:${app.rsrc-server.port}
  auth-server:
    protocol: http
    host: auth-server
    port: 39003
    base-url: ${app.auth-server.protocol}://${app.auth-server.host}:${app.auth-server.port}
