client:
  ssl:
    trust-store: ssl/truststore.jks
    trust-store-password: secret
    # use javax.net.debug values here, like all, ssl...
    net-debug: none

app.client.protocol: https
app.rsrc-server.protocol: https
app.auth-server.protocol: https