server:
  ssl:
    enabled: true
    key-store: ssl/server-identity.jks
    key-password: secret
    key-store-password: secret
    trust-store: ssl/server-truststore.jks
    trust-store-password: secret
