server:
  port: 39002

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

app.protocol: http

spring:
#  profiles.active: ssl
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.protocol}://localhost:39003/oauth2/jwks
