server:
  port: ${app.rsrc-server.port:39002}

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
    sample.util.PropertiesDumper: debug
    org.zalando.logbook: trace
#    org.springframework.boot.autoconfigure: debug

app:
  auth-server:
    protocol: http
    host: localhost
    port: 39003

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.auth-server.protocol}://${app.auth-server.host}:${app.auth-server.port}/oauth2/jwks
