server.port: 39004

app.protocol: http

spring.security.oauth2.client:
  registration.local:
    provider: spring
    authorization-grant-type: client_credentials
    client-id: messaging-client
    client-secret: secret
    scope: message.read,message.write
  provider.spring.token-uri: ${app.protocol}://localhost:39003/oauth2/token

oauth2.client.registration.local.ssl-enabled: false

test.client:
  host: http://localhost:39005
  base.url: ${app.protocol}://localhost:39002
  test.path: /messages