server:
  port: 39003

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
    # org.springframework.boot.autoconfigure: debug
