server:
  port: ${app.client.port:39001}
  ssl:
    enabled: false

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
    org.apache.http: debug
    httpclient.wire: debug
    sample.util.PropertiesDumper: debug
    org.zalando.logbook: trace
    org.springframework.web.reactive.function.client.ExchangeFunctions: trace
    reactor.netty.http.client: trace
    # org.springframework.boot.autoconfigure: debug

spring:
  http.log-request-details: true
  mvc:.log-request-details: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          messaging-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized"
            scope: message.read,message.write
          messaging-client-client-credentials:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: message.read,message.write
          messaging-client-password:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: password
            scope: message.read,message.write

        provider:
          spring:
            authorization-uri: ${app.auth-server.base-url}/oauth2/authorize
            token-uri: ${app.auth-server.base-url}/oauth2/token

messages:
  base-uri: "${app.rsrc-server.base-url}/messages"
