spring.profiles.include: ssl

#server:
#  ssl:
#    trust-store: classpath:server-truststore.jks
#    trust-store-password: secret
#    client-auth: need

client:
  ssl:
    two-way-authentication-enabled: true
    key-store: classpath:client-identity.jks
    key-store-password: secret